# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile-coding-challenge' do
  use_frameworks!

  pod 'Alamofire', 'alamofire5'
  pod 'Kingfisher', '~> 4.0'
  pod 'SnapKit', '~> 4.0.0'
  # pod 'SwiftyJSON'


  target 'mobile-coding-challengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mobile-coding-challengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

